impact/urls.py
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.urls import include, path

from impact import views

urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n')),
    path('admin/', admin.site.urls),

    path('api/', include('metrics_api.urls'))
]

urlpatterns += i18n_patterns(
    path('', views.LandingView.as_view(), name='landing'),
    path('terms/', views.TermsView.as_view(), name='terms'),
    path('', include('accounts.urls')),
    path('metrics/', include('metrics.urls')),
)

metrics/urls.py
from django.urls import path

from . import views

app_name = 'metrics'

urlpatterns = [
    path('run/', views.run, name='run'),

    path(
        'compare/<uuid:actual_report_uuid>/<uuid:previous_report_uuid>',
        views.compare_reports,
        name='compare'
    ),

    path('results/<uuid:pk>', views.ReportView.as_view(), name='results'),
    path(
        'results/<uuid:pk>/<section>/<metric>',
        views.ReportView.as_view(),
        name='results'
    ),

    path('', views.ReportListView.as_view(), name='reports'),
]

impact/models.py
from django.db import models


class TimeStampedModel(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True

impact/views.py
from django.views.generic import TemplateView


class LandingView(TemplateView):
    """Display the landing page of the website."""
    template_name = 'impact/index.html'


class TermsView(TemplateView):
    """Display the terms and conditions page of the website."""
    template_name = 'impact/terms.html'

templates/impact/index.html
{% extends 'layouts/base.html' %}
{% load static %}
{% load i18n %}

{% block title %}Landing{% endblock %}

{% block content %}
  <!-- Hero -->
  <section
    class="pt-24 md:mt-0 md:h-screen flex flex-col justify-center text-center md:text-left md:flex-row
    md:justify-between md:items-center lg:px-48 md:px-12 px-4 bg-white">
    <div class="md:flex-1 md:mr-10">
      <h1 class="font-pt-serif text-5xl font-bold mb-7">
        {% trans "It's time to test" %}
        <span class="imp-bg-underline1 bg-left-bottom bg-no-repeat pb-2 imp-bg-100%">
          {% trans "your website" %}
        </span>
      </h1>
      <p class="font-pt-serif font-normal mb-7">
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Laborum harum
        tempore consectetur voluptas, cumque nobis laboriosam voluptatem.
      </p>
      <form method="POST" action="{% url 'metrics:run' %}" class="flex font-montserrat">
        {% csrf_token %}
        <label for="page_url" class="hidden">page URL:</label>
        <input
          type="text" name="page_url" id="page_url" placeholder="https://www.yoursite.com"
          class="{% if request.GET.error %}border-red-600{% else %}border-black{% endif %} w-full px-6 py-4 border-r-0 border-2"
        />
        <button type="submit" class="border-2 w-24 border-black hover:text-white hover:bg-black duration-300">Test it!
        </button>
      </form>
      {% if request.GET.error %}
        {% load metric_tags %}
        {% display_input_error request.GET.error %}
      {% endif %}
    </div>
    <div class="flex justify-around md:block mt-8 md:mt-0 md:flex-1">
      <div class="relative">
        <img src="{% static 'assets/sparks-top-left.svg' %}" alt="sparks" class="absolute -top-16 -left-10">
      </div>
      <div class="imp-browser-mockup">
        <div class="h-48 w-96 md:w-full md:h-80">
          {# ? TODO: Find out an image? #}
        </div>
      </div>
      <div class="relative">
        <img src="{% static 'assets/sparks-bottom-right.svg' %}" alt="sparks" class="absolute -bottom-10 -right-6">
      </div>
    </div>
  </section>
  <!-- How it works -->
  <section class="imp-section-size bg-black text-white">
    <div>
      <h2 class="imp-secondary-title imp-bg-underline2 imp-bg-100%">How it works</h2>
    </div>
    <div class="flex flex-col md:flex-row">
      <div class="flex-1 mx-8 flex flex-col items-center my-4">
        <div class="border-2 rounded-full bg-white text-black h-12 w-12 flex justify-center items-center mb-3">
          1
        </div>
        <h3 class="font-montserrat font-medium text-xl mb-2">Type your URL</h3>
        <p class="text-center font-montserrat">
          Lorem ipsum dolor, sit amet consectetur adipisicing elit.
        </p>
      </div>
      <div class="flex-1 mx-8 flex flex-col items-center my-4">
        <div class="border-2 rounded-full bg-white text-black h-12 w-12 flex justify-center items-center mb-3">
          2
        </div>
        <h3 class="font-montserrat font-medium text-xl mb-2">Wait for Analysis</h3>
        <p class="text-center font-montserrat">
          Lorem ipsum dolor, sit amet consectetur adipisicing elit.
        </p>
      </div>
      <div class="flex-1 mx-8 flex flex-col items-center my-4">
        <div class="border-2 rounded-full bg-white text-black h-12 w-12 flex justify-center items-center mb-3">
          3
        </div>
        <h3 class="font-montserrat font-medium text-xl mb-2">Get your report</h3>
        <p class="text-center font-montserrat">
          Lorem ipsum dolor, sit amet consectetur adipisicing elit.
        </p>
      </div>
    </div>
  </section>
  <!-- Features -->
  <section class="imp-section-size bg-white">
    <div>
      <h2 class="imp-secondary-title imp-bg-underline3 imp-bg-100%">Features</h2>
    </div>
    <div class="md:grid md:grid-cols-2 md:grid-rows-2">

      <div class="flex items-start font-montserrat my-6 mr-10">
        <img src="{% static 'assets/heart.svg' %}" alt="heart icon" class="h-7 mr-4">
        <div>
          <h3 class="font-semibold text-2xl">Feature #1</h3>
          <p>
            Lorem ipsum dolor sit amet consectetur, adipisicing elit.
            Quisquam voluptate praesentium tenetur earum repellendus! Dicta
            culpa consequuntur saepe quibusdam labore, est ex ducimus
            tempore, quos illum officiis, pariatur ea placeat.
          </p>
        </div>
      </div>

      <div class="flex items-start font-montserrat my-6 mr-10">
        <img src="{% static 'assets/heart.svg' %}" alt="" class="h-7 mr-4">
        <div>
          <h3 class="font-semibold text-2xl">Feature #2</h3>
          <p>
            Lorem ipsum dolor sit amet consectetur, adipisicing elit.
            Quisquam voluptate praesentium tenetur earum repellendus! Dicta
            culpa consequuntur saepe quibusdam labore, est ex ducimus
            tempore, quos illum officiis, pariatur ea placeat.
          </p>
        </div>
      </div>

      <div class="flex items-start font-montserrat my-6 mr-10">
        <img src="{% static 'assets/heart.svg' %}" alt="" class="h-7 mr-4">
        <div>
          <h3 class="font-semibold text-2xl">Feature #3</h3>
          <p>
            Lorem ipsum dolor sit amet consectetur, adipisicing elit.
            Quisquam voluptate praesentium tenetur earum repellendus! Dicta
            culpa consequuntur saepe quibusdam labore, est ex ducimus
            tempore, quos illum officiis, pariatur ea placeat.
          </p>
        </div>
      </div>

      <div class="flex items-start font-montserrat my-6 mr-10">
        <img src="{% static 'assets/heart.svg' %}" alt="" class="h-7 mr-4">
        <div>
          <h3 class="font-semibold text-2xl">Feature #4</h3>
          <p>
            Lorem ipsum dolor sit amet consectetur, adipisicing elit.
            Quisquam voluptate praesentium tenetur earum repellendus! Dicta
            culpa consequuntur saepe quibusdam labore, est ex ducimus
            tempore, quos illum officiis, pariatur ea placeat.
          </p>
        </div>
      </div>

    </div>
  </section>
{% endblock %}

{% block scripts %}
  {{ block.super }}
  <script src="{% static 'js/handle-input-error.js' %}"></script>
{% endblock %}

templates/impact/terms.html
{% extends 'layouts/base.html' %}

{% block title %}Mentions légales{% endblock %}

{% block content %}
  <div class="container offset-header">
    <h1>Impact &ndash; Mentions légales</h1>
    <p class="text-muted">
      Merci d'utiliser Impact ! Nous sommes heureux que vous soyez là. Veuillez lire attentivement cet
      accord sur les conditions de service avant d'accéder à Impact ou de l'utiliser.
      Comme il s'agit d'un contrat très important entre nous et nos utilisateurs, nous avons essayé de le rendre
      aussi clair que possible. Pour votre commodité, nous avons présenté ces conditions sous la forme d'un
      court résumé non contraignant, suivi des conditions légales complètes.
    </p>
    <h5>Hébergeur du site internet</h5>
    <p class="text-muted">
      Le site est hébergé par <strong>Heroku</strong> dont le siège social est situé au
      &laquo; Inc. 650 7th Street San Francisco, CA 94103, USA &raquo;. Leur site web est disponible à l'adresse
      suivante : <a href="https://www.heroku.com">https://www.heroku.com</a>
    </p>

    <h2>Crédits</h2>
    <div></div>
  </div>
{% endblock %}