impact/urls.py
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.urls import include, path

from impact import views

urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n')),
    path('admin/', admin.site.urls),

    path('api/', include('metrics_api.urls'))
]

urlpatterns += i18n_patterns(
    path('', views.LandingView.as_view(), name='landing'),
    path('terms/', views.TermsView.as_view(), name='terms'),
    path('', include('accounts.urls')),
    path('metrics/', include('metrics.urls')),
)

metrics/urls.py
from django.urls import path

from . import views

app_name = 'metrics'

urlpatterns = [
    path('run/', views.run, name='run'),

    path(
        'compare/<uuid:actual_report_uuid>/<uuid:previous_report_uuid>',
        views.compare_reports,
        name='compare'
    ),

    path('results/<uuid:pk>', views.ReportView.as_view(), name='results'),
    path(
        'results/<uuid:pk>/<section>/<metric>',
        views.ReportView.as_view(),
        name='results'
    ),

    path('', views.ReportListView.as_view(), name='reports'),
]

metrics/models.py
import uuid as uuid
from django.db import models

from accounts.models import User
from impact.models import TimeStampedModel
from metrics.utils import calculate_note


class Report(TimeStampedModel):
    uuid = models.UUIDField('model identifier', default=uuid.uuid4, primary_key=True)
    url = models.CharField(max_length=255, null=False)
    score = models.PositiveIntegerField(null=True)
    metrics = models.JSONField()

    user = models.ForeignKey(User, blank=True, null=True, on_delete=models.CASCADE)
    previous_report = models.ForeignKey(
        'self', on_delete=models.SET_NULL, null=True, blank=True
    )

    class Meta:
        ordering = ('uuid',)

    def get_note(self) -> str:
        return calculate_note(self.score)

metrics/views.py
import logging

from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import SuspiciousOperation, PermissionDenied
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.views.generic import View, ListView
from phantomas import PhantomasError

from .core import Runner
from .models import Report

logger = logging.getLogger(__name__)


def run(request):
    url = request.POST.get('page_url')

    runner = Runner(url)

    try:
        score, results = runner.start()

        report = Report(url=url, score=score, metrics=results)
    except PhantomasError as e:
        logger.warning("An error occurred when running Phantomas :\n %s", e.args[0])
        if "URL" in e.args[0]:
            error_code = "url"
        else:
            error_code = "network"

        return redirect(f"{reverse('landing')}?error={error_code}")

    if request.user.is_authenticated:
        report.user = request.user
        previous_report = Report.objects \
            .filter(url=url, user=request.user).order_by('-created_at').first()

        report.previous_report = previous_report

    report.save()

    return redirect(reverse('metrics:results', args=(report.pk,)), permanent=True)


@login_required
def compare_reports(request, actual_report_uuid, previous_report_uuid):
    previous_report = Report.objects.get(pk=previous_report_uuid)
    actual_report = Report.objects.get(pk=actual_report_uuid)

    if request.user.id != previous_report.user_id \
            or request.user.id != actual_report.user_id:
        raise PermissionDenied('One of the reports are not owned by yourself.')

    if previous_report.url != actual_report.url:
        raise SuspiciousOperation("Reports are not related.")

    context = {
        "actual_report": actual_report,
        "previous_report": previous_report,
    }

    return render(request, 'metrics/compare.html', context)


class ReportView(View):
    object: Report

    def setup(self, request, *args, **kwargs):
        super().setup(request, *args, **kwargs)

        self.object = get_object_or_404(Report, pk=kwargs.get('pk'))

    def get_render_data(self):
        ctx = {}
        template_name = 'metrics/results.html'
        section_name: str = self.kwargs.get('section')

        if section_name in self.object.metrics and self.kwargs.get('metric'):
            ctx['metric'] = self.get_metric(self.object.metrics[section_name])
            ctx['report_uuid'] = self.object.pk
            template_name = 'metrics/metric.html'
        else:
            ctx['report'] = self.object

        return template_name, ctx

    def get(self, request, *args, **kwargs):
        template_name, context = self.get_render_data()

        return render(request, template_name, context)

    def get_metric(self, section: dict):
        if not isinstance(section, dict):
            return

        metric = self.kwargs['metric']

        return {
            'value': section['metrics'].get(metric),
            'rule': section['rules'].get(metric),
        }


class ReportListView(LoginRequiredMixin, ListView):
    model = Report
    template_name = 'metrics/report-list.html'
    context_object_name = 'report_list'

    def get_queryset(self):
        """Return the list of items for this view."""
        return super() \
            .get_queryset() \
            .filter(user=self.request.user)

metrics/templates/metrics/compare.html
{% extends "layouts/base.html" %}
{% load static %}

{% block title %}Compare reports{% endblock %}

{% block content %}
  <div class="flex flex-col">
    <div class="flex justify-center items-center space-x-4 my-6">
      <abbr id="switcher" class="no-underline hover:text-white hover:bg-black rounded border"
            title="Switch to the other report">
        <span class="flex justify-center items-center px-2 pb-2 text-5xl
        cursor-pointer">&#8646;</span>
      </abbr>
    </div>

    <div id="actual_report">
      <div class="flex justify-center text-xl">
        <p>Report of {{ actual_report.created_at|date:"Y-m-d \a\t H:m" }} (Most recent)</p>
      </div>
      {% include 'metrics/report/report.html' with report=actual_report %}
    </div>

    <div id="previous_report" class="hidden">
      <div class="flex justify-center text-xl">
        <p>Report of {{ previous_report.created_at|date:"Y-m-d \a\t H:m" }} (Previous)</p>
      </div>
      {% include 'metrics/report/report.html' with report=previous_report %}
    </div>
  </div>
{% endblock %}

{% block scripts %}
  {{ block.super }}
  <script src="{% static 'js/compare-reports.js' %}"></script>
{% endblock %}

metrics/templates/metrics/cta.html
<div class="flex justify-center items-center space-x-4 mt-6">
  <abbr class="no-underline hover:text-white hover:bg-black rounded border" title="Test again">
    <a href="{% url 'landing' %}"
       class="flex justify-center items-center px-2 pb-2 text-5xl
        cursor-pointer">&#11148;</a>
  </abbr>

  {% if report.previous_report %}
    <abbr class="no-underline hover:text-white hover:bg-black rounded border" title="Compare with the last report">
      <a href="{% url 'metrics:compare' report.pk report.previous_report_id %}"
         class="flex justify-center items-center px-2 pb-2 text-5xl
        cursor-pointer">&#8646;</a>
    </abbr>
  {% endif %}
</div>

metrics/templates/metrics/metric.html
{% extends 'layouts/base.html' %}
{% load i18n %}
{% load static %}
{% load metric_filters %}

{% block title %}{{ metric.rule.title }}{% endblock %}

{% block content %}
  <div class="container mx-auto">
    <div class="flex flex-col items-center mt-6">
      <abbr class="no-underline hover:text-white hover:bg-black rounded border" title="Go Back">
        <a href="{% url 'metrics:results' report_uuid %}"
           class="flex justify-center items-center px-2 pb-2 text-5xl
        cursor-pointer">
          &#8592;
        </a>
      </abbr>
      <div class="mt-8 flex flex-col items-center justify-center">
        <p class="text-xl">{{ metric.rule.title }}</p>
        <div
          class="flex text-3xl mt-2 justify-center rounded-full px-6 py-2 uppercase note-{% get_note metric.rule metric.value %}">
          {% get_note metric.rule metric.value %}
        </div>
        <p class="mb-6">{{ metric.rule.score }} / 100</p>
        <p>Your value: {{ metric.value }}</p>
        <p>It must be at {{ metric.rule.good_threshold }} or less to get 100/100</p>
        <p class="m-6">{{ metric.rule.message }}</p>
      </div>
    </div>
  </div>
{% endblock %}

metrics/templates/metrics/report-list.html
{% extends 'layouts/base.html' %}
{% load static %}
{% load i18n %}

{% block title %}{% trans 'My Reports' %}{% endblock %}

{% block content %}
  <div class="container mx-auto">
    <div class="flex flex-wrap mt-6 space-x-12">
      {% for report in report_list %}
        <a href="{% url 'metrics:results' report.pk %}" class="border p-4 rounded hover:bg-gray-100">
          <div class="flex items-center border-b py-2">
            <div class="note-{{ report.get_note|lower }} flex flex-col items-center py-4 px-8 rounded">
              <p class="text-2xl">{{ report.score }}</p>
              <div class="border-b w-full"></div>
              <p class="text-2xl">100</p>
            </div>
            <div class="flex flex-col justify-center ml-4">
              <span class="text-lg">Tested URL:</span>
              <span>{{ report.url }}</span>
              <p class="text-right mt-2">{{ report.created_at|date:"Y-m-d" }}</p>
            </div>
          </div>
        </a>
      {% empty %}
        <div class="flex w-full items-center justify-center">
          <p class="text-2xl">{% trans "No reports were found." %}</p>
        </div>
      {% endfor %}
    </div>
  </div>
{% endblock %}

metrics/templates/metrics/results.html
{% extends 'layouts/base.html' %}
{% load static %}

{% block title %}Metrics Result{% endblock %}

{% block content %}
  <div class="container mx-auto">
    {% include 'metrics/cta.html' %}
    {% include 'metrics/report/report.html' with report=report %}
  </div>
{% endblock %}

{% block scripts %}
  {{ block.super }}
  <script src="{% static 'js/metrics-collapse.js' %}"></script>
{% endblock %}